I2C_DRIVER_REQUIRED = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom
POINTING_DEVICE_MOTION_PIN = GP28
POINTING_DEVICE_MOTION_PIN_ACTIVE_LOW = yes
ENCODER_MAP_ENABLE = yes
SRC += maxtouch.c
