#pragma once

#undef MATRIX_ROW_PINS
#define MATRIX_ROW_PINS \
    { B8, B13, B14, B15, B9 }
#undef MATRIX_COL_PINS
#define MATRIX_COL_PINS \
    { B1, B2, B3, B4, B5, B6 }

#ifdef RGBLIGHT_ENABLE
#    define RGB_DI_PIN A3
#    undef RGBLED_NUM
#    define RGBLED_NUM 40
#    define WS2812_PWM_DRIVER PWMD2
#    define WS2812_PWM_CHANNEL 4
#    define WS2812_PWM_PAL_MODE 1
#    define WS2812_DMA_STREAM STM32_DMA1_STREAM2
#    define WS2812_DMA_CHANNEL 2
#    define RGBLIGHT_EFFECT_BREATHING
#    define RGBLIGHT_EFFECT_RAINBOW_MOOD
#    define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#    define RGBLIGHT_EFFECT_SNAKE
#    define RGBLIGHT_EFFECT_KNIGHT
#    define RGBLIGHT_EFFECT_CHRISTMAS
#    define RGBLIGHT_EFFECT_STATIC_GRADIENT
#    define RGBLIGHT_EFFECT_RGB_TEST
#    define RGBLIGHT_EFFECT_ALTERNATING
#    define RGBLIGHT_EFFECT_TWINKLE
#endif

#define AUDIO_PIN A5
#define AUDIO_PIN_ALT A4
#define AUDIO_PIN_ALT_AS_NEGATIVE

#undef BACKLIGHT_PIN
#define BACKLIGHT_PIN B0
#define BACKLIGHT_PWM_DRIVER PWMD3
#define BACKLIGHT_PWM_CHANNEL 3
#define BACKLIGHT_PAL_MODE 2
