MCU = STM32F303
BOARD = QMK_PROTON_C

BOOTLOADER = stm32-dfu

BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = pwm

RGBLIGHT_SUPPORTED = yes
RGBLIGHT_ENABLE = yes
WS2812_DRIVER = pwm

AUDIO_SUPPORTED = yes
AUDIO_ENABLE = yes
AUDIO_DRIVER  = dac_additive

